#!/bin/bash
cd ..
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=6 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=12 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=19 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=100 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=140 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=190 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=400 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=800 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=1600 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="10ms" --queueDiscSize=38 --sim_duration=1000 "
