#!/bin/bash
cd ..
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=10 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=20 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=40 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=90 --sim_duration=1000 "


./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=180 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=720 --sim_duration=5000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=5000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=5000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=5000 "

./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpBbrV2" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
./waf --run "examples/tcp/my-dumbbell --flows=1 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=5400 --sim_duration=5000 "
