#!/bin/bash
cd ..
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=60 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=120 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=182 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=360 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=700 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=1800 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=200 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=500 --sim_duration=200 "

./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpBbr" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpCubic" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpNewReno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpWestwood" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVegas" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpYeah" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpVeno" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
./waf --run "examples/tcp/my-dumbbell --flows=3 --sim_name="AggregPerf" --TcpType="TcpIllinois" --btlBW="10Mbps" --btlDelay="100ms" --queueDiscSize=300 --sim_duration=200 "
