#!/bin/bash
cd ..
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=0 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=600 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1200 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=1820 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3600 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=7000 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=12000 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=18200 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=2000 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=5000 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="100ms" --queueDiscSize=3000 --sim_duration=1000 "