#!/bin/bash
cd ..
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=0 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=60 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=120 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=180 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=360 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=700 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1200 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=1800 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=200 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=500 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=300 --sim_duration=1000 "

./waf --run "examples/tcp/my-dumbbell --TcpType="TcpBbr" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpCubic" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpNewReno" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpWestwood" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpVegas" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "
./waf --run "examples/tcp/my-dumbbell --TcpType="TcpYeah" --btlBW="100Mbps" --btlDelay="10ms" --queueDiscSize=182 --sim_duration=1000 "