# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('my-dumbbell', 
        ['core','internet', 'point-to-point', 'mobility', 'point-to-point-layout', 'applications'])
    module.source = [
        'model/my-dumbbell.cc',
        'helper/my-dumbbell-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('my-dumbbell')
    module_test.source = [
        'test/my-dumbbell-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/my-dumbbell-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'my-dumbbell'
    headers.source = [
        'model/my-dumbbell.h',
        'helper/my-dumbbell-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

